### PR TITLE
Add go.yml

### LINKED ISSUE #4: Setup Github CI

### PR DESCRIPTION
**Pull request by Startouf**
fixes #4

### CODE REVIEW

**Comment by Startouf** [comment]
@mourtisma j'ai besoin de tips de ta part, car là y'a aucun test qui se lance, cf https://github.com/gjgd/dont-slack-evil/pull/5/checks?check_run_id=463085901#step:6:6

**Comment by gjgd** [comment]
```golang
go test dont-slack-evil/helpers
```
works but maybe there is a better way to run all packages in the module

**Comment by mourtisma** [comment]
The right command is `go test ./...`.
`./...` means 'run the command on the current dir and all of its subdirs'

**Comment by Startouf** [comment]
@mourtisma je merge dans ta branche alors

**Pull request merged**
